import type { Metadata } from 'next'
import { createClient } from '@/lib/supabase/server'
import { normalizeRoadmap, normalizeCompletedSteps } from '@/lib/roadmap/types'
import RoadmapExperience from '@/components/roadmap/RoadmapExperience'

export const metadata: Metadata = {
  title: 'Stratégie & Roadmap — Voraly',
  description: "Planifiez votre stratégie freelance avec l'IA Voraly.",
}

export default async function RoadmapPage() {
  // Load any roadmap previously generated by the n8n workflow plus the user's
  // completed checkpoints, so returning users land straight on their plan with
  // progression already restored. RLS restricts this to the owner's row.
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  let initialSteps: ReturnType<typeof normalizeRoadmap> = []
  let initialCompleted: number[] = []
  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('ai_roadmap, completed_steps')
      .eq('id', user.id)
      .maybeSingle()
    initialSteps = normalizeRoadmap(profile?.ai_roadmap)
    initialCompleted = normalizeCompletedSteps(profile?.completed_steps)
  }

  return (
    <RoadmapExperience
      initialSteps={initialSteps}
      initialCompleted={initialCompleted}
      userId={user?.id ?? null}
    />
  )
}
